---
title: 'Coursera Reproducible Research: Evauating Activity Monitoring Data'
author: "Darion Lawson"
output:
  html_document:
    toc: yes
---

### Introduction

This document provides a description about the scripts, the data, and provides instructions to run the project. This project used data from a personal activity monitoring device. The purpose of the project was to evaluate the data and answer specific project-related questions. The results are presented in a report created using R Markdown and Knitr.

Environment: This script was developed and tested on:

* Windows 64-bit operating system
* IDE: RStudio Version 0.98.1062

### Directory Inventory
The project directory contains the following files:

* README.Rmd: this file that explains the project.
* PA1_template.html: the generated report as HTML generated from R Markdown source file.
* PA1_template.Rmd: the report source R markdown file.
* PA1_template.R: R file to used to generate the HTML from the source PA1_template.Rmd file.



