---
title: "Coursera Exploratory Data Analysis Project 2"
author: "Darion Lawson"
output:
  html_document:
    toc: yes
---

# Overview

This directory contains the source and output files that I created for Project 2 for the [Coursera Exploratory data analysis course](https://www.coursera.org/course/exdata) taught by professors at John Hopkins University.

The purpose of this project was to answer specific pollution-related questions using data from the National Emissions Inventory database about fine particulate matter pollution in the United States over the 10 year period 1999 to 2008.

The original submission was much more concise that the the files here. After the course, I spent some time investigating other approaches to aggregated the data, and create plots.

# Directory Contents:

* exdata_data_NEI_data.zip: is the original data source file supplied for the project.

* Source_Classification_Code.rds: is the Source Classification Code table that provides a mapping from the SCC digit values in the Emissions table (in summarySCC_PM25.rds) to the actual name of the PM2.5 source.

* summarySCC_PM25.rds: is the PM2.5 Emissions Data for 1999, 2002, 2005, and 2008.

* Each of the R files (Plot1.R, Plot2.R, Plot3.R, Plot4.R, Plot5.R, Plot6.R) creates one or plots to answer a different question.

* Each of the PNG image files is an image export of one plot corresponding to the respective R file (eg. plot1.1.png was created using Plot1.R)

# Definitions
These definitions are taken from (http://www.epa.gov/ttn/chief/net/2008inventory.html)

Some of the definitions 
* Point: "..sources that are individually inventoried and usually located at a fixed, stationary location, although portable sources such as some asphalt or rock crushing operations are also included"

* NonPoint: "...sources which individually are too small in magnitude or too numerous to inventory as individual point sources, and which can often be estimated more accurately as a single aggregate source for a County or Tribal area. Examples are residential heating and consumer solvent use"

* OnRoad and NonRoad: are mobile sources of pollution. OnRoad are from sources that travel  travel via roadway. NonRoad are from sources that do not travel by roadway.
