---
title: "Coursera Getting and Cleaning Data Project"
author: "Darion Lawson"
output:
  html_document:
    toc: yes
---
### Introduction

This document provides a description about the scripts, the data, and provides instructions to run the project. 

Environment: This script was developed and tested on:

* Windows 64-bit operating system
* IDE: RStudio Version 0.98.1062

Inventory: The project directory contains the following files:

* README.md: this document, explaining the project contents.
* run_analysis.R: the primary execution file
* getvalues.R: user defined function that takes a data.frame and regular expression string, and returns column values that match the regexp string
* cleanfeaturenames.R: takes a dataframe and parses the column names into valid values.
* CodeBook.md: explains the data.
* project01_tidy.txt: the tidy dataset that is generated by this code. 

### To run these scripts

Assumptions: 

* all project files must be downloaded into the same directory. 
* the source datafiles will be downloaded and extracted in the same directory as the project files.

To run this:
1. Open run_analysis.R
2. Locate the line with value: #**TODO:
3. Change the argument value in the setwd() function to the location of the run_analysis.R 
   and other project files.
4. Every line in the run_analysis.R file must be executed equentially. 
   Each task is organized into sections, and each task is described as a separate step.
5. The tidy dataset will be written to the project working directory (in setwd function call).

### List of code execution steps

#### Preparation

* STEP 1: set up the environment dependencies
* STEP 2: download and unzip the source data files

#### Set up the training data

* STEP 3: get the training data from x_train.txt
* STEP 4: get the list of features from features.txt and trim whitespace
* STEP 5: convert featurename values to valid column names
* STEP 6: use the list of features to create column names for the training data
* STEP 7: get activity id labels for traindata from y_train.txt
* STEP 8: get the subject Ids from subject_train.txt
* STEP 9: use the activitytrain data to add a new column for activityId
* STEP 10: use the subjecttrain to add a new column for subjectId

#### Set up the test Data

* STEP 11: get the test data 
* STEP 12: use the list of features to create column names for the test data
* STEP 13: get activity id labels for test data from y_test.txt
* STEP 14: get the subject Ids from subject_test.txt
* STEP 15: use the activitytest data to add a new column for activityId
* STEP 16: use the subjecttest to add a new column for subjectId

#### Merge the training data and the test data into one dataframe

* STEP 17: merge the training and test data

#### Aggregate the data based on Activity Id AND SubjectId

* STEP 18: get the column names that contain the value - 'mean'
* STEP 19: use descriptive activity names to name the activities in the data set
* STEP 20: create a subset of the data with the variables for mean 
* STEP 21: convert datatype to double
* STEP 22: add activityId and subjectId columns#
* STEP 23: calculate mean of each ActivityId and Subject Id combination

#### Create a molten data set and correct clean up the data 

* STEP 24: melt the data frame
* STEP 25: create and populate a new timeScaleType column as raw or fourier 
* STEP 26: populate measurementType column  as x-axis, y-axis, z-axis, or magnitude
* STEP 27: populate sensor column as gyro or accelerometer
* STEP 28: populate sensor subtype column as body or gravity
* STEP 29: populate movement type column as normal or jerk
* STEP 30: populate valueType column as mean or std.dev 
* STEP 31: reorder columns
* STEP 32: remove the variable column with original variable name 

#### Create a Tidy data set 

* STEP 33: cast meltedReadings to move mean and std.dev into separate columns
* STEP 34: export tidy data set to txt file in working directory

The data and supporting information for this project is courtesy of:

[1] Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and Jorge L. Reyes-Ortiz. 
Human Activity Recognition on Smartphones using a Multiclass Hardware-Friendly Support Vector Machine. 
International Workshop of Ambient Assisted Living (IWAAL 2012). Vitoria-Gasteiz, Spain. Dec 2012
